spring:
 application:
  name: MovieAPI
 datasource:
  url: jdbc:mysql://localhost:3306/movies
  username: root
  password: Tiger
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
    hibernate:
     format_sql: true


project:
 poster: posters/

base:
 url: "http://localhost:8080"

#logging:
# level:
#  root: DEBUG
#  org.springframework.web: DEBUG